<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/LlmProxy.Domain/LlmProxy.Domain.csproj" />
    <ProjectReference Include="../../../src/LlmProxy.Application/LlmProxy.Application.csproj" />
    <ProjectReference Include="../../../src/LlmProxy.Infrastructure/LlmProxy.Infrastructure.csproj" />
    <ProjectReference Include="../../../src/LlmProxy.Api/LlmProxy.Api.csproj" />
    <ProjectReference Include="../../../src/LlmProxy.UpdateAgent/LlmProxy.UpdateAgent.csproj" />
    <ProjectReference Include="../../../src/LlmProxy.NodeAgent/LlmProxy.NodeAgent.csproj" />
  </ItemGroup>
</Project>
