namespace LlmProxy.Api.Admin;

public sealed record DeployableModelDescriptor(
    string Id,
    string DisplayName,
    string ProviderModelName,
    string Family,
    string License,
    string SourceUrl,
    double ParameterBillions,
    int ContextTokens,
    string Precision,
    double MinimumGpuMemoryGiB,
    double RecommendedGpuMemoryGiB,
    double MinimumSystemMemoryGiB,
    double RecommendedSystemMemoryGiB,
    double DiskGiB,
    int MinimumGpuCount,
    int RecommendedGpuCount,
    bool SupportsStreaming,
    bool SupportsTools,
    IReadOnlyList<string> Tags,
    string Notes,
    string Runtime = "vllm");

public static class DeployableModelCatalog
{
    // Resource figures are conservative planning estimates for serving with vLLM.
    // The compatibility engine treats them as guidance, not as a benchmark guarantee.
    public static IReadOnlyList<DeployableModelDescriptor> All { get; } =
    [
        new(
            "qwen3-4b",
            "Qwen3 4B",
            "Qwen/Qwen3-4B",
            "Qwen3",
            "Apache-2.0",
            "https://huggingface.co/Qwen/Qwen3-4B",
            4.0,
            131072,
            "BF16",
            10,
            16,
            16,
            24,
            12,
            1,
            1,
            true,
            true,
            ["general", "reasoning", "multilingual", "compact"],
            "Small general-purpose model; a good first deployment for constrained accelerators."),
        new(
            "qwen3-8b",
            "Qwen3 8B",
            "Qwen/Qwen3-8B",
            "Qwen3",
            "Apache-2.0",
            "https://huggingface.co/Qwen/Qwen3-8B",
            8.0,
            131072,
            "BF16",
            20,
            24,
            32,
            48,
            22,
            1,
            1,
            true,
            true,
            ["general", "reasoning", "coding", "multilingual"],
            "Balanced model for general chat, code and reasoning workloads."),
        new(
            "qwen3-14b",
            "Qwen3 14B",
            "Qwen/Qwen3-14B",
            "Qwen3",
            "Apache-2.0",
            "https://huggingface.co/Qwen/Qwen3-14B",
            14.0,
            131072,
            "BF16",
            34,
            48,
            48,
            64,
            34,
            1,
            1,
            true,
            true,
            ["general", "reasoning", "coding", "multilingual"],
            "Higher-quality general model; leave headroom for KV cache when sizing concurrency."),
        new(
            "qwen3-32b",
            "Qwen3 32B",
            "Qwen/Qwen3-32B",
            "Qwen3",
            "Apache-2.0",
            "https://huggingface.co/Qwen/Qwen3-32B",
            32.0,
            131072,
            "BF16",
            72,
            96,
            96,
            128,
            76,
            1,
            2,
            true,
            true,
            ["general", "reasoning", "coding", "large"],
            "Large model. Multi-GPU tensor parallelism is recommended unless one accelerator has ample memory."),
        new(
            "mistral-7b-instruct-v03",
            "Mistral 7B Instruct v0.3",
            "mistralai/Mistral-7B-Instruct-v0.3",
            "Mistral",
            "Apache-2.0",
            "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
            7.0,
            32768,
            "BF16",
            18,
            24,
            24,
            32,
            20,
            1,
            1,
            true,
            true,
            ["general", "instruct", "compact"],
            "Established Apache-2.0 instruct model with moderate hardware requirements."),
        new(
            "qwen3-4b-awq-vllm",
            "Qwen3 4B AWQ 4-bit (vLLM)",
            "Qwen/Qwen3-4B-AWQ",
            "Qwen3",
            "Apache-2.0",
            "https://huggingface.co/Qwen/Qwen3-4B-AWQ",
            4.0,
            32768,
            "AWQ INT4",
            6,
            12,
            16,
            24,
            6,
            1,
            1,
            true,
            true,
            ["awq", "quantized", "coding", "benchmark-baseline"],
            "Native 32K context; evaluate longer YaRN contexts separately. Compare against GGUF and BF16."),
        new(
            "qwen3-8b-awq-vllm",
            "Qwen3 8B AWQ 4-bit (vLLM)",
            "Qwen/Qwen3-8B-AWQ",
            "Qwen3",
            "Apache-2.0",
            "https://huggingface.co/Qwen/Qwen3-8B-AWQ",
            8.0,
            32768,
            "AWQ INT4",
            10,
            16,
            24,
            32,
            12,
            1,
            1,
            true,
            true,
            ["awq", "quantized", "coding", "benchmark-baseline"],
            "Native context baseline; checkpoint fit and sustainable parallelism require real tests."),
        new(
            "qwen3-4b-awq-sglang",
            "Qwen3 4B AWQ 4-bit (SGLang experimental)",
            "Qwen/Qwen3-4B-AWQ",
            "Qwen3",
            "Apache-2.0",
            "https://huggingface.co/Qwen/Qwen3-4B-AWQ",
            4.0,
            32768,
            "AWQ INT4",
            6,
            12,
            16,
            24,
            6,
            1,
            1,
            true,
            true,
            ["awq", "quantized", "sglang", "experimental"],
            "Experimental SGLang serving; must pass Responses/SSE/tool-call and capacity acceptance.",
            "sglang"),
        new(
            "qwen3-4b-gguf-q4",
            "Qwen3 4B GGUF Q4_K_M",
            "ggml-org/Qwen3-4B-GGUF:Q4_K_M",
            "Qwen3",
            "Apache-2.0",
            "https://huggingface.co/ggml-org/Qwen3-4B-GGUF",
            4.0,
            131072,
            "Q4_K_M",
            0,
            6,
            8,
            16,
            8,
            0,
            1,
            true,
            true,
            ["gguf", "quantized", "cpu-offload", "experimental"],
            "Experimental llama.cpp profile; context is shared across parallel slots and capacity requires benchmarking.",
            "llama.cpp")
    ];

    public static DeployableModelDescriptor? Find(string id) =>
        All.FirstOrDefault(model => string.Equals(model.Id, id, StringComparison.OrdinalIgnoreCase));
}
