import { FormEvent, useEffect, useState } from 'react'
import { api } from './api'
import { Modal, Tabs } from './UiPrimitives'
import type { CapacitySnapshot, Model, Node, NodeHardwareMetricsSnapshot } from './types'

type Props = { nodes: Node[]; hardware: NodeHardwareMetricsSnapshot[]; canWrite?: boolean; refresh: () => Promise<void>; embedded?: boolean }
const emptyCapacity: CapacitySnapshot = { nodes: [], deployments: [] }

export default function HardwareExperience({ nodes, hardware, canWrite = true, refresh, embedded = false }: Props) {
  const [tab, setTab] = useState<'telemetry' | 'capacity' | 'benchmarks'>('telemetry')
  const [endpointOpen, setEndpointOpen] = useState(false)
  const [profileOpen, setProfileOpen] = useState(false)
  const [nodeId, setNodeId] = useState(nodes[0]?.id ?? '')
  const [baseAddress, setBaseAddress] = useState('')
  const [saved, setSaved] = useState(false)
  const [capacity, setCapacity] = useState<CapacitySnapshot>(emptyCapacity)
  const [models, setModels] = useState<Model[]>([])
  const [deploymentId, setDeploymentId] = useState('')
  const [recommended, setRecommended] = useState(1)
  const [p95Ttft, setP95Ttft] = useState('')
  const [p95Duration, setP95Duration] = useState('')
  const [outputTokensPerSecond, setOutputTokensPerSecond] = useState('')
  const [benchmarkSource, setBenchmarkSource] = useState('')
  const [measuredAt, setMeasuredAt] = useState(nowForInput())
  const [capacityMessage, setCapacityMessage] = useState<string | null>(null)
  const [capacityNodeId, setCapacityNodeId] = useState('')
  const [physicalLimit, setPhysicalLimit] = useState(1)
  const [capacityEditOpen, setCapacityEditOpen] = useState(false)

  useEffect(() => { if (!nodeId && nodes[0]) setNodeId(nodes[0].id) }, [nodeId, nodes])
  useEffect(() => { const selected = nodes.find(node => node.id === nodeId); setBaseAddress(selected?.hardwareMetricsBaseAddress ?? '') }, [nodeId, nodes])
  useEffect(() => { void loadCapacity() }, [])
  useEffect(() => {
    const selected = capacity.deployments.find(item => item.id === deploymentId)
    if (!selected) return
    setRecommended(selected.recommendedMaxConcurrency ?? selected.effectiveMaxConcurrency)
    setP95Ttft(optionalInput(selected.benchmarkP95TtftMilliseconds)); setP95Duration(optionalInput(selected.benchmarkP95DurationMilliseconds)); setOutputTokensPerSecond(optionalInput(selected.sustainableOutputTokensPerSecond)); setBenchmarkSource(selected.benchmarkSource ?? ''); setMeasuredAt(selected.benchmarkMeasuredAtUtc ? dateForInput(selected.benchmarkMeasuredAtUtc) : nowForInput())
  }, [capacity.deployments, deploymentId])

  async function loadCapacity() { const capacityRequest = typeof api.capacity === 'function' ? api.capacity() : Promise.resolve(emptyCapacity); const [nextCapacity, nextModels] = await Promise.all([capacityRequest, api.models()]); setCapacity(nextCapacity); setModels(nextModels); setDeploymentId(current => current || nextCapacity.deployments[0]?.id || '') }
  async function submit(event: FormEvent) { event.preventDefault(); if (!nodeId) return; await api.updateNodeHardwareMetrics(nodeId, baseAddress.trim() || null); setSaved(true); await refresh() }
  async function clear() { if (!nodeId) return; await api.updateNodeHardwareMetrics(nodeId, null); setBaseAddress(''); setSaved(true); await refresh() }
  async function saveCapacityProfile(event: FormEvent) { event.preventDefault(); if (!deploymentId) return; await api.updateCapacityProfile(deploymentId, { recommendedMaxConcurrency: recommended, p95TtftMilliseconds: nullableNumber(p95Ttft), p95DurationMilliseconds: nullableNumber(p95Duration), sustainableOutputTokensPerSecond: nullableNumber(outputTokensPerSecond), benchmarkSource: benchmarkSource.trim(), measuredAtUtc: new Date(measuredAt).toISOString() }); setCapacityMessage('Capacity recommendation saved. Active production limits were not changed.'); setProfileOpen(false); await loadCapacity(); await refresh() }
  async function applyCapacityProfile() { if (!deploymentId) return; await api.applyCapacityProfile(deploymentId); setCapacityMessage('Recommended deployment capacity applied explicitly.'); await loadCapacity(); await refresh() }
  async function clearCapacityProfile() { if (!deploymentId) return; await api.clearCapacityProfile(deploymentId); setCapacityMessage('Capacity recommendation cleared. Active production limits were not changed.'); await loadCapacity(); await refresh() }
  function openCapacityEdit(id: string) { const node = nodes.find(item => item.id === id); if (!node) return; setCapacityNodeId(id); setPhysicalLimit(node.maxConcurrency); setCapacityEditOpen(true) }
  async function savePhysicalCapacity(event: FormEvent) { event.preventDefault(); const node = nodes.find(item => item.id === capacityNodeId); if (!node) return; await api.updateNode(node.id, { name: node.name, baseAddress: node.baseAddress, weight: node.weight, maxConcurrency: physicalLimit }); setCapacityMessage(`${node.name} physical concurrency updated to ${physicalLimit}.`); setCapacityEditOpen(false); await refresh(); await loadCapacity() }

  const available = hardware.filter(item => item.available)
  const modelNames = new Map(models.map(model => [model.id, model.publicName])); const nodeNames = new Map(nodes.map(node => [node.id, node.name]))
  const selectedDeployment = capacity.deployments.find(item => item.id === deploymentId); const selectedNode = selectedDeployment ? capacity.nodes.find(item => item.id === selectedDeployment.nodeId) : undefined; const recommendationExceedsNode = Boolean(selectedNode && recommended > selectedNode.maxConcurrency)

  return <div className="stack compactPage">
    {!embedded && <section className="panel pageToolbar"><div><h2>Hardware operations</h2><p className="muted">Telemetry, physical capacity and benchmark evidence are separated so operators can focus on one task at a time.</p></div>{tab === 'telemetry' && canWrite && <button className="primary" onClick={() => setEndpointOpen(true)}>Configure telemetry endpoint</button>}{tab === 'benchmarks' && canWrite && <button className="primary" disabled={capacity.deployments.length === 0} onClick={() => setProfileOpen(true)}>Manage capacity recommendation</button>}</section>}
    {embedded && <section className="panel pageToolbar"><div><h2>Capacity & telemetry</h2><p className="muted">Physical capacity is a hard simultaneous-request ceiling. Telemetry observes the machine; benchmark profiles provide evidence for per-model limits.</p></div>{tab === 'telemetry' && canWrite && <button className="primary" onClick={() => setEndpointOpen(true)}>Configure telemetry endpoint</button>}{tab === 'benchmarks' && canWrite && <button className="primary" disabled={capacity.deployments.length === 0} onClick={() => setProfileOpen(true)}>Manage capacity recommendation</button>}</section>}
    <Tabs value={tab} onChange={setTab} items={[{ value: 'telemetry', label: 'Telemetry', count: available.length }, { value: 'capacity', label: 'Physical capacity', count: capacity.nodes.length }, { value: 'benchmarks', label: 'Benchmark profiles', count: capacity.deployments.length }]} />
    {capacityMessage && <div className="notice">{capacityMessage}</div>}

    {tab === 'telemetry' && <>
      <section className="cards cardsFive"><Metric label="Configured nodes" value={nodes.filter(node => node.hardwareMetricsBaseAddress).length} /><Metric label="Telemetry available" value={available.length} /><Metric label="GPUs observed" value={available.reduce((total, item) => total + item.gpuCount, 0)} /><Metric label="Max GPU util" value={formatMax(available.map(item => item.maxGpuUtilizationPercent), '%')} /><Metric label="Max temperature" value={formatMax(available.map(item => item.maxTemperatureCelsius), ' °C')} /></section>
      <section className="panel"><div className="panelTitle"><h2>Hardware telemetry</h2><span>NVIDIA/DCGM · observational only</span></div><div className="tableScroll"><table><thead><tr><th>Node</th><th>Collector</th><th>GPU</th><th>GPU util</th><th>FB memory</th><th>Temperature</th><th>Power</th><th>Last sample</th></tr></thead><tbody>{nodes.map(node => { const item = hardware.find(snapshot => snapshot.nodeId === node.id); return <tr key={node.id}><td><strong>{node.name}</strong><div className="muted mono">{node.hardwareMetricsBaseAddress ?? 'DCGM endpoint not configured'}</div></td><td>{item ? (item.available ? 'Available' : 'Unavailable') : (node.hardwareMetricsBaseAddress ? 'Waiting' : 'Not configured')}{item?.error && <div className="muted">{item.error}</div>}</td><td>{item?.available ? item.gpuCount : '—'}</td><td>{item?.available ? `${formatOptional(item.averageGpuUtilizationPercent)} avg · ${formatOptional(item.maxGpuUtilizationPercent)} max` : '—'}</td><td>{item?.available ? `${formatMiB(item.framebufferUsedMiB)} used · ${formatRatio(item.framebufferUsageRatio)}` : '—'}</td><td>{item?.available ? formatTemperature(item.maxTemperatureCelsius) : '—'}</td><td>{item?.available ? formatPower(item.totalPowerUsageWatts) : '—'}</td><td>{formatDate(item?.collectedAtUtc ?? item?.lastAttemptAtUtc)}</td></tr>})}</tbody></table></div><div className="secretBox hardwareHint"><strong>Routing isolation</strong><p>DCGM availability, GPU utilization, temperature and power do not currently change node health or routing score. vLLM queue/KV pressure remains the scheduling signal until benchmark evidence justifies otherwise.</p></div></section>
    </>}

    {tab === 'capacity' && <section className="panel"><div className="panelTitle"><h2>Physical concurrency</h2><span>Current distributed admission · all deployments on a machine share one ceiling</span></div><div className="tableScroll"><table><thead><tr><th>Hardware</th><th>Active now</th><th>Maximum simultaneous requests</th><th>Available</th><th>Coordination</th><th>At saturation</th><th>Action</th></tr></thead><tbody>{capacity.nodes.map(item => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.activeRequests}</td><td><strong>{item.maxConcurrency}</strong></td><td>{item.remaining}</td><td>{item.coordinationAvailable === false ? 'Unavailable' : item.capacityProvider ?? 'local'}{item.localActiveRequests !== undefined && item.capacityProvider === 'redis' ? <div className="muted">this gateway: {item.localActiveRequests}</div> : null}</td><td><code>429 capacity_exhausted</code></td><td>{canWrite && <button onClick={() => openCapacityEdit(item.id)}>Edit capacity</button>}</td></tr>)}</tbody></table></div><div className="notice">This is request concurrency, not a people limit. For example, 10 means at most 10 simultaneous inference requests across every model runtime on this hardware. A Copilot user can generate more than one concurrent request.</div></section>}

    {tab === 'benchmarks' && <section className="panel"><div className="panelTitle"><h2>Benchmark capacity profiles</h2><span>Measured recommendation ≠ active production limit</span></div><div className="tableScroll"><table><thead><tr><th>Model / node</th><th>Active</th><th>Deployment limit</th><th>Recommended</th><th>P95 TTFT</th><th>Throughput</th><th>Evidence</th><th>Actions</th></tr></thead><tbody>{capacity.deployments.map(item => <tr key={item.id}><td><strong>{modelNames.get(item.modelId) ?? short(item.modelId)}</strong><div className="muted">{nodeNames.get(item.nodeId) ?? short(item.nodeId)}</div></td><td>{item.activeRequests}</td><td>{item.effectiveMaxConcurrency}</td><td>{item.recommendedMaxConcurrency ?? '—'}</td><td>{formatMilliseconds(item.benchmarkP95TtftMilliseconds)}</td><td>{formatTokensPerSecond(item.sustainableOutputTokensPerSecond)}</td><td><span className="mono">{item.benchmarkSource ?? 'not measured'}</span><div className="muted">{formatDate(item.benchmarkMeasuredAtUtc)}</div></td><td className="actions"><button onClick={() => { setDeploymentId(item.id); setProfileOpen(true) }}>Edit</button><button disabled={!item.recommendedMaxConcurrency || (capacity.nodes.find(node => node.id === item.nodeId)?.maxConcurrency ?? 0) < (item.recommendedMaxConcurrency ?? 0)} onClick={() => { setDeploymentId(item.id); void api.applyCapacityProfile(item.id).then(async () => { setCapacityMessage('Recommended deployment capacity applied explicitly.'); await loadCapacity(); await refresh() }) }}>Apply</button></td></tr>)}</tbody></table></div></section>}

    <Modal open={endpointOpen} title="Configure hardware telemetry" description="Optional DCGM endpoint, independent from the inference service root." onClose={() => setEndpointOpen(false)}><form className="formPanel" onSubmit={async event => { await submit(event); setEndpointOpen(false) }}><label>Inference node<select aria-label="Hardware Inference node" value={nodeId} onChange={event => { setNodeId(event.target.value); setSaved(false) }} disabled={nodes.length === 0}>{nodes.map(node => <option key={node.id} value={node.id}>{node.name}</option>)}</select></label><label>Hardware metrics service root<input aria-label="Hardware metrics service root" value={baseAddress} onChange={event => { setBaseAddress(event.target.value); setSaved(false) }} placeholder="http://10.0.0.21:9400" /></label><div className="modalActions"><button type="button" className="secondary" onClick={() => void clear()}>Clear endpoint</button><button className="primary" disabled={!nodeId}>Save endpoint</button></div>{saved && <div className="notice">Hardware telemetry configuration updated.</div>}</form></Modal>

    <Modal open={profileOpen} title="Capacity recommendation" description="Store benchmark evidence first. Applying it is a separate action." onClose={() => setProfileOpen(false)}><form className="formPanel" onSubmit={saveCapacityProfile}><label>Deployment<select aria-label="Capacity deployment" value={deploymentId} onChange={event => { setDeploymentId(event.target.value); setCapacityMessage(null) }} disabled={capacity.deployments.length === 0}>{capacity.deployments.map(item => <option key={item.id} value={item.id}>{modelNames.get(item.modelId) ?? short(item.modelId)} → {nodeNames.get(item.nodeId) ?? short(item.nodeId)}</option>)}</select></label><label>Recommended max concurrency<input aria-label="Recommended max concurrency" type="number" min="1" value={recommended} onChange={event => setRecommended(Number(event.target.value))} required /></label><label>P95 TTFT (ms)<input aria-label="Capacity P95 TTFT" type="number" min="0" step="0.1" value={p95Ttft} onChange={event => setP95Ttft(event.target.value)} /></label><label>P95 duration (ms)<input aria-label="Capacity P95 duration" type="number" min="0" step="0.1" value={p95Duration} onChange={event => setP95Duration(event.target.value)} /></label><label>Sustainable output tokens/sec<input aria-label="Capacity output tokens per second" type="number" min="0" step="0.1" value={outputTokensPerSecond} onChange={event => setOutputTokensPerSecond(event.target.value)} /></label><label>Benchmark source<input aria-label="Benchmark source" value={benchmarkSource} onChange={event => setBenchmarkSource(event.target.value)} required placeholder="benchmark-results/llmproxy-benchmark-...json" /></label><label>Measured at<input aria-label="Benchmark measured at" type="datetime-local" value={measuredAt} onChange={event => setMeasuredAt(event.target.value)} required /></label>{selectedDeployment && <div className="secretBox"><strong>Current limits</strong><p>Deployment active limit: {selectedDeployment.effectiveMaxConcurrency}</p><p>Physical node limit: {selectedNode?.maxConcurrency ?? '—'}</p>{recommendationExceedsNode && <p className="error">Recommendation exceeds the current physical node limit. Save is allowed as evidence, but Apply will be rejected until the node limit is explicitly increased.</p>}</div>}<div className="modalActions"><button type="button" className="secondary" disabled={!selectedDeployment?.recommendedMaxConcurrency} onClick={() => void clearCapacityProfile()}>Clear recommendation</button><button className="primary" disabled={!deploymentId}>Save recommendation</button><button type="button" className="secondary" disabled={!selectedDeployment?.recommendedMaxConcurrency || recommendationExceedsNode} onClick={() => void applyCapacityProfile()}>Apply recommended</button></div></form></Modal>
    <Modal open={capacityEditOpen} title="Edit physical concurrency" description="Set the machine-wide simultaneous inference request ceiling. Increase it only as benchmark/runtime evidence shows the hardware can sustain more work." onClose={() => setCapacityEditOpen(false)}><form className="formPanel" onSubmit={savePhysicalCapacity}><label>Maximum simultaneous inference requests<input aria-label="Maximum simultaneous inference requests" type="number" min="1" value={physicalLimit} onChange={event => setPhysicalLimit(Number(event.target.value))} required /></label><div className="notice">Authorized users are managed separately in Users & Access. Request/token quotas are managed in Usage & Governance.</div><div className="modalActions"><button type="button" className="secondary" onClick={() => setCapacityEditOpen(false)}>Cancel</button><button className="primary">Save capacity</button></div></form></Modal>
  </div>
}

function Metric({ label, value }: { label: string; value: string | number }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div> }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleString() : '—' }
function formatOptional(value?: number | null) { return value === null || value === undefined ? '—' : `${value.toFixed(1)}%` }
function formatRatio(value?: number | null) { return value === null || value === undefined ? '—' : `${(value * 100).toFixed(1)}%` }
function formatMiB(value?: number | null) { if (value === null || value === undefined) return '—'; return value >= 1024 ? `${(value / 1024).toFixed(1)} GiB` : `${Math.round(value)} MiB` }
function formatTemperature(value?: number | null) { return value === null || value === undefined ? '—' : `${value.toFixed(0)} °C` }
function formatPower(value?: number | null) { return value === null || value === undefined ? '—' : `${value.toFixed(0)} W` }
function formatMilliseconds(value?: number | null) { return value === null || value === undefined ? '—' : `${Math.round(value)} ms` }
function formatTokensPerSecond(value?: number | null) { return value === null || value === undefined ? '—' : `${value.toFixed(1)} tok/s` }
function formatMax(values: Array<number | null | undefined>, suffix: string) { const numbers = values.filter((value): value is number => value !== null && value !== undefined); return numbers.length === 0 ? '—' : `${Math.max(...numbers).toFixed(0)}${suffix}` }
function nullableNumber(value: string) { return value.trim() === '' ? null : Number(value) }
function optionalInput(value?: number | null) { return value === null || value === undefined ? '' : String(value) }
function short(value: string) { return value.length > 12 ? `${value.slice(0, 8)}…` : value }
function nowForInput() { return dateForInput(new Date().toISOString()) }
function dateForInput(value: string) { const date = new Date(value); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16) }
