import type { ReactNode } from 'react'

const help: Record<string, { title: string; body: ReactNode }> = {
  dashboard: { title: 'Dashboard', body: <><p>Operational summary of the gateway: fleet health, active requests, logical models, deployments and recent inference latency.</p><p>Use this page to decide where to drill down. It does not change runtime configuration.</p></> },
  nodes: { title: 'Inference nodes', body: <><p>The active-node table is the operational home for inference service roots, health, concurrency and upstream authentication. Add-node and credential configuration open in focused dialogs instead of occupying the page permanently.</p><p>Disable a node before deleting it; deletion is rejected while active requests remain. Node max concurrency remains a hard admission limit.</p></> },
  hardware: { title: 'Hardware', body: <><p>Use the Telemetry, Physical capacity and Benchmark profiles tabs to inspect only the hardware signal you need. DCGM endpoint configuration opens in a dialog.</p><p>Capacity profiles are recommendations until an administrator explicitly applies them; hardware telemetry remains observational and does not directly change routing.</p></> },
  'model-management': { title: 'Model & Hardware', body: <><p>The Hardware inventory and Deploy models tabs keep machine inspection separate from model lifecycle. The management-agent installer can be downloaded directly from this page.</p><p>Compatibility is an estimate. Stopping or removing a managed model disables its deployment before the remote runtime is changed so routing fails safe.</p></> },
  models: { title: 'Models & deployments', body: <><p>A logical model is the stable client-facing name accepted by <code>/v1/chat/completions</code> and <code>/v1/responses</code>; the provider model name is the runtime identifier LlmProxy forwards upstream.</p><p>The unified workspace can be read in both directions: model → deployment nodes and node → deployed models. Administrators can publish aliases, deploy to additional nodes, deploy to every active node, or enable/disable routing participation.</p></> },
  deployments: { title: 'Models & deployments', body: <><p>Legacy navigation resolves to the unified Models & Deployments workspace. A deployment binds one logical model to one inference node, while enabled state, health, weight and available concurrency determine whether routing can select it.</p></> },
  routing: { title: 'Routing', body: <><p>Weighted least loaded considers configured capacity, health, recent TTFT/failure feedback and optional live vLLM pressure. Round robin variants are available for simpler routing.</p><p>Rate limiting is caller governance; capacity admission protects the inference fleet. They intentionally produce different telemetry.</p></> },
  credentials: { title: 'API credentials', body: <><p>Credential scope is explicit: organization keys are shared workload credentials, personal keys belong to one Entra identity, and Usage Groups only add governance/accounting. Newly generated or rotated secrets use <code>lp_org_</code> or <code>lp_usr_</code> prefixes so scope is visible to operators.</p><p>Administrators can reveal application-encrypted recoverable secrets, rotate keys and revoke them. Older keys remain valid with their historical prefix and can be rotated to adopt the new scoped format.</p></> },
  users: { title: 'Users & Access', body: <><p>The Users tab handles day-to-day access lifecycle; Provisioning & identity contains the Entra admission policy and identity guidance. Manual user creation opens in a dialog.</p><p>Stable identity is Entra tenant ID + object ID (<code>tid</code> + <code>oid</code>); email is display metadata only. Disabling a user blocks the portal immediately and revokes that user's currently active personal API keys.</p></> },
  metrics: { title: 'Request metrics', body: <><p>Aggregated inference telemetry shows status, routing attempts, TTFT, duration and token usage. The request table starts with the newest 20 records and supports model, node, credential and success/error filters plus pagination.</p><p>Full request/response payloads remain intentionally separated into administrator-only Content Logs.</p></> },
  logs: { title: 'Content logs', body: <><p>Administrator-only encrypted-at-rest request and response payloads for Chat Completions, Responses and System One. The page auto-refreshes every two seconds.</p><p>Retention is configurable from 10 to 180 days. Cleanup runs automatically every four hours.</p></> },
  playground: { title: 'Playground', body: <><p>Model chat and System One classifier diagnostics are split into tabs so each workflow has its own compact workspace. Model tests pass through LlmProxy routing and capacity admission but bypass caller rate limits because they are administrative diagnostics.</p><p>Each upstream diagnostic is written to Content Logs so its exact request and response can be inspected later.</p></> },
  audit: { title: 'Audit trail', body: <><p>Administrative configuration and sensitive-control actions. API-key secret reveals, retention changes and manual cleanup runs are audited without recording the revealed secret itself.</p></> },
  help: { title: 'Endpoint & platform guide', body: <><p>Copy-ready endpoint examples plus an explanation of authentication, routing, capacity, rate limiting, classifier forwarding, observability and retention.</p></> },
  governance: { title: 'Usage & Governance', body: <><p>Usage reporting, group/credential assignment and quota policy are separated into dedicated tabs. Create actions open dialogs instead of permanently occupying the page.</p><p>Request-rate and token-budget governance still runs before routing and capacity admission.</p></> },
  releases: { title: 'Release notes & updates', body: <><p>Shows the installed version, published immutable releases and the update plan attached to each release.</p><p>Administrators can launch an immediate update or schedule one. The host Update Agent executes outside the gateway container so the operation survives container replacement. A release can use the standard installer or a bundled custom update procedure; arbitrary commands cannot be entered from the UI.</p></> },
  me: { title: 'My dashboard', body: <><p>Your self-service area shows personal API keys, 30-day usage, request limits and recent calls attributed to your own credentials.</p><p>Portal admission is controlled by the Users & Access registry. A disabled user cannot enter and existing personal keys are revoked when the administrator disables the account.</p></> }
}

export default function PageDocumentation({ page }: { page: string }) {
  const item = help[page] ?? { title: 'This page', body: <p>Operational controls and information for LlmProxy.</p> }
  return <details className="pageDocumentation">
    <summary>Page documentation · {item.title}</summary>
    <div className="pageDocumentationBody">{item.body}</div>
  </details>
}
