import type { ReactNode } from 'react'

const help: Record<string, { title: string; body: ReactNode }> = {
  dashboard: { title: 'Dashboard', body: <><p>Operational summary of the gateway: fleet health, active requests, logical models, deployments and recent inference latency.</p><p>Use this page to decide where to drill down. It does not change runtime configuration.</p></> },
  infrastructure: { title: 'Infrastructure', body: <><p>Infrastructure is the node-centric control plane: fleet access, physical concurrency, telemetry, hardware inventory and managed model lifecycle live together. One node represents one physical machine; model runtimes may listen on different ports through deployment runtime roots.</p><p>Physical concurrency counts simultaneous inference requests, not people. User/group/key quotas remain in Usage & Governance. Benchmark profiles are evidence until explicitly applied.</p></> },
  nodes: { title: 'Infrastructure', body: <><p>The legacy Inference Nodes route now opens the unified Infrastructure workspace.</p></> },
  hardware: { title: 'Infrastructure', body: <><p>The legacy Hardware route now opens the unified Infrastructure workspace.</p></> },
  'model-management': { title: 'Infrastructure', body: <><p>The legacy Model & Hardware route now opens the unified Infrastructure workspace.</p></> },
  models: { title: 'Models & deployments', body: <><p>A logical model has a surface: <strong>OpenAI</strong> for <code>/v1/chat/completions</code>/<code>/v1/responses</code>, or <strong>System One</strong> for typed classifier calls on <code>/v1/systemone</code>. Both use the same node/deployment topology, capacity admission and routing controls.</p><p>The unified workspace can be read in both directions: model → deployment nodes and node → deployed models. Administrators can publish aliases, deploy to additional nodes, deploy to every active node, or enable/disable routing participation.</p></> },
  deployments: { title: 'Models & deployments', body: <><p>Legacy navigation resolves to the unified Models & Deployments workspace. A deployment binds one logical model to one inference node, while enabled state, health, weight and available concurrency determine whether routing can select it.</p></> },
  routing: { title: 'Routing', body: <><p>Weighted least loaded considers configured capacity, health, recent TTFT/failure feedback and optional live vLLM pressure. Round robin variants are available for simpler routing.</p><p>Rate limiting is caller governance; capacity admission protects the inference fleet. They intentionally produce different telemetry.</p></> },
  credentials: { title: 'API credentials', body: <><p>Credential scope is explicit: organization keys are shared workload credentials, personal keys belong to one Entra identity, and Usage Groups only add governance/accounting. Newly generated or rotated secrets use <code>lp_org_</code> or <code>lp_usr_</code> prefixes so scope is visible to operators.</p><p>Administrators can reveal application-encrypted recoverable secrets, rotate keys and revoke them. Older keys remain valid with their historical prefix and can be rotated to adopt the new scoped format.</p></> },
  users: { title: 'Users & Access', body: <><p>The Users tab handles day-to-day access lifecycle; Provisioning & identity contains the Entra admission policy and identity guidance. Manual user creation opens in a dialog.</p><p>Stable identity is Entra tenant ID + object ID (<code>tid</code> + <code>oid</code>); email is display metadata only. Disabling a user blocks the portal immediately and revokes that user's currently active personal API keys.</p></> },
  metrics: { title: 'Request metrics', body: <><p>Aggregated inference telemetry shows status, routing attempts, TTFT, duration and token usage. The request table starts with the newest 20 records and supports model, node, credential and success/error filters plus pagination.</p><p>Full request/response payloads remain intentionally separated into administrator-only Content Logs.</p></> },
  logs: { title: 'Request audit', body: <><p>Administrators can search and inspect application-encrypted request/response payloads across users, credentials, models, surfaces, status and time. Decrypted detail responses are never cached.</p><p>Retention is administrator-controlled from 10 days through 11 years (4015 days), with automatic cleanup every four hours. Normal users can inspect only payloads attributable to their own personal API keys from My dashboard.</p></> },
  playground: { title: 'Playground', body: <><p>OpenAI model chat and System One classifier diagnostics are split into tabs. Each selector only shows models published for that surface, and both diagnostics pass through the same deployment routing and capacity admission used by production traffic.</p><p>Each upstream diagnostic is written to Content Logs so its exact request, selected node and response can be inspected later.</p></> },
  audit: { title: 'Audit trail', body: <><p>Administrative configuration and sensitive-control actions. API-key secret reveals, retention changes and manual cleanup runs are audited without recording the revealed secret itself.</p></> },
  help: { title: 'Endpoint & platform guide', body: <><p>Copy-ready endpoint examples plus an explanation of authentication, routing, capacity, rate limiting, classifier forwarding, observability and retention.</p></> },
  governance: { title: 'Usage & Governance', body: <><p>Usage reporting, group/credential assignment and quota policy are separated into dedicated tabs. Create actions open dialogs instead of permanently occupying the page.</p><p>Request-rate and token-budget governance still runs before routing and capacity admission.</p></> },
  releases: { title: 'Release notes & updates', body: <><p>Shows the installed version, published immutable releases and the update plan attached to each release. A jump to a later target expands to the complete ascending release chain, so an intermediate custom migration cannot be skipped.</p><p>Administrators can keep updates manual, check every five minutes and apply latest ASAP, or run latest on a nightly, weekly or monthly policy. Update now and one-off scheduling remain available. The host Update Agent executes outside the gateway container so container replacement does not terminate the update.</p></> },
  me: { title: 'My dashboard', body: <><p>Your self-service area shows personal API keys, 30-day usage, request limits, recent calls and an inspectable request audit for payloads attributable to your own personal credentials.</p><p>Request/response bodies remain application-encrypted at rest and cannot be used to inspect organization/shared credentials or another user's calls. Portal admission is controlled by the Users & Access registry.</p></> }
}

export default function PageDocumentation({ page }: { page: string }) {
  const item = help[page] ?? { title: 'This page', body: <p>Operational controls and information for LlmProxy.</p> }
  return <details className="pageDocumentation">
    <summary>Page documentation · {item.title}</summary>
    <div className="pageDocumentationBody">{item.body}</div>
  </details>
}
