import type { ReactNode } from 'react'

const help: Record<string, { title: string; body: ReactNode }> = {
  dashboard: { title: 'Dashboard', body: <><p>Operational summary of the gateway: fleet health, active requests, logical models, deployments and recent inference latency.</p><p>Use this page to decide where to drill down. It does not change runtime configuration.</p></> },
  nodes: { title: 'Inference nodes', body: <><p>Registers inference service roots, health probes, node-level concurrency and optional upstream bearer credentials.</p><p>Node max concurrency is a hard admission limit. A request can receive <code>429 capacity_exhausted</code> before it reaches vLLM when all eligible capacity is occupied.</p></> },
  hardware: { title: 'Hardware', body: <><p>Shows optional DCGM and runtime telemetry separately from routing. Capacity profiles are recommendations until an administrator explicitly applies them.</p></> },
  'model-management': { title: 'Model & Hardware', body: <><p>Administrator control plane for prepared hardware. It reads CPU, RAM, disk and GPU inventory from the node-management agent, evaluates the deployable model catalog, and controls install/start/stop/remove lifecycle.</p><p>Compatibility is an estimate. Stopping or removing a managed model disables its deployment before the remote runtime is changed so routing fails safe.</p></> },
  models: { title: 'Logical models', body: <><p>Logical models are the client-facing names accepted by <code>/v1/chat/completions</code> and <code>/v1/responses</code>. The provider model name is what LlmProxy sends to the selected runtime.</p><p>Use Playground to send a real non-streaming chat test through routing and capacity admission.</p></> },
  deployments: { title: 'Deployments', body: <><p>A deployment binds one logical model to one inference node. Effective selection also considers enabled state, health, configured weight and available node/deployment concurrency.</p></> },
  routing: { title: 'Routing', body: <><p>Weighted least loaded considers configured capacity, health, recent TTFT/failure feedback and optional live vLLM pressure. Round robin variants are available for simpler routing.</p><p>Rate limiting is caller governance; capacity admission protects the inference fleet. They intentionally produce different telemetry.</p></> },
  credentials: { title: 'API credentials', body: <><p>Keys authenticate inference calls. LlmProxy stores a one-way authentication hash plus an application-encrypted copy of newly created/rotated secrets so administrators can reveal/copy them later.</p><p>Older keys created before encrypted retention cannot be recovered; rotate them once to enable Reveal.</p></> },
  users: { title: 'Users & Access', body: <><p>Controls whether authenticated Entra end users are registered automatically on first portal access or must be pre-registered by an administrator.</p><p>Stable identity is Entra tenant ID + object ID (<code>tid</code> + <code>oid</code>); email is display metadata only. Disabling a user blocks the portal immediately and revokes that user's currently active personal API keys.</p></> },
  metrics: { title: 'Request metrics', body: <><p>Aggregated inference telemetry: status, routing attempts, TTFT, duration and token usage. Full request/response payloads are intentionally separated into administrator-only Content Logs.</p></> },
  logs: { title: 'Content logs', body: <><p>Administrator-only encrypted-at-rest request and response payloads for Chat Completions, Responses and System One. The page auto-refreshes every two seconds.</p><p>Retention is configurable from 10 to 180 days. Cleanup runs automatically every four hours.</p></> },
  playground: { title: 'Playground', body: <><p>Runs live diagnostics against active logical models and the configured System One classifier. Model tests pass through LlmProxy routing and capacity admission but bypass caller rate limits because they are administrative diagnostics.</p><p>Each upstream diagnostic is written to Content Logs so its exact request and response can be inspected later.</p></> },
  audit: { title: 'Audit trail', body: <><p>Administrative configuration and sensitive-control actions. API-key secret reveals, retention changes and manual cleanup runs are audited without recording the revealed secret itself.</p></> },
  help: { title: 'Endpoint & platform guide', body: <><p>Copy-ready endpoint examples plus an explanation of authentication, routing, capacity, rate limiting, classifier forwarding, observability and retention.</p></> },
  governance: { title: 'Usage & Governance', body: <><p>Maps credentials and Entra users to usage groups, request-rate policies and token budgets. These controls run before routing and capacity admission.</p></> },
  releases: { title: 'Release notes & updates', body: <><p>Shows the installed version, published immutable releases and the update plan attached to each release.</p><p>Administrators can launch an immediate update or schedule one. The host Update Agent executes outside the gateway container so the operation survives container replacement. A release can use the standard installer or a bundled custom update procedure; arbitrary commands cannot be entered from the UI.</p></> },
  me: { title: 'My dashboard', body: <><p>Your self-service area shows personal API keys, 30-day usage, request limits and recent calls attributed to your own credentials.</p><p>Portal admission is controlled by the Users & Access registry. A disabled user cannot enter and existing personal keys are revoked when the administrator disables the account.</p></> }
}

export default function PageDocumentation({ page }: { page: string }) {
  const item = help[page] ?? { title: 'This page', body: <p>Operational controls and information for LlmProxy.</p> }
  return <details className="pageDocumentation">
    <summary>Page documentation · {item.title}</summary>
    <div className="pageDocumentationBody">{item.body}</div>
  </details>
}
