import { useEffect, useState } from 'react'
import type { Model, Node } from './types'
import type { RequestAuditSummary } from './requestAuditTypes'
import { Modal } from './UiPrimitives'

export default function RequestAuditSummaryModal({ summary, models, nodes, busy, onClose, onRegenerate }: {
  summary: RequestAuditSummary | null
  models: Model[]
  nodes: Node[]
  busy: boolean
  onClose: () => void
  onRegenerate: (logicalModel?: string | null, nodeId?: string | null) => Promise<void>
}) {
  const [logicalModel, setLogicalModel] = useState('')
  const [nodeId, setNodeId] = useState('')

  useEffect(() => {
    setLogicalModel(summary?.logicalModel ?? '')
    setNodeId(summary?.nodeId ?? '')
  }, [summary])

  if (!summary) return null
  const nodeName = summary.nodeId ? nodes.find(node => node.id === summary.nodeId)?.name : undefined

  return <Modal
    open
    title="Request summary"
    description={`Saved administrator-only summary · ${new Date(summary.updatedAtUtc).toLocaleString()}`}
    onClose={onClose}
    className="requestSummaryModal"
  >
    <div className="requestSummaryBody">
      <div className="summaryMetaGrid">
        <div><span>Model</span><strong>{summary.logicalModel}</strong></div>
        <div><span>Node</span><strong>{nodeName ?? summary.nodeId ?? 'Automatic routing'}</strong></div>
        <div><span>Generated by</span><strong>{summary.generatedBy}</strong></div>
        <div><span>Generated</span><strong>{new Date(summary.generatedAtUtc).toLocaleString()}</strong></div>
      </div>

      <pre className="summaryText">{summary.summary}</pre>

      <div className="summaryRegenerate">
        <div>
          <h3>Generate a new summary</h3>
          <p className="muted">Choose a model/node for this run, or leave either selector automatic. The new result replaces the saved summary for this request audit.</p>
        </div>
        <div className="formGridTwo">
          <label>Model
            <select aria-label="Summary regeneration model" value={logicalModel} onChange={event => setLogicalModel(event.target.value)}>
              <option value="">Configured default / automatic</option>
              {models.filter(model => model.enabled && model.surface === 'OpenAi').map(model => <option key={model.id} value={model.publicName}>{model.publicName}</option>)}
            </select>
          </label>
          <label>Node
            <select aria-label="Summary regeneration node" value={nodeId} onChange={event => setNodeId(event.target.value)}>
              <option value="">Configured default / automatic routing</option>
              {nodes.filter(node => node.enabled).map(node => <option key={node.id} value={node.id}>{node.name}</option>)}
            </select>
          </label>
        </div>
        <div className="modalActions">
          <button type="button" className="secondary" onClick={onClose}>Close</button>
          <button type="button" className="primary" disabled={busy} onClick={() => void onRegenerate(logicalModel || null, nodeId || null)}>
            {busy && <span className="miniSpinner buttonSpinner" aria-hidden="true" />}Regenerate summary
          </button>
        </div>
      </div>
    </div>
  </Modal>
}
